### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by ashwintiwari88** [fadhlichan/adakerja-messenger-bot#1]
[+] clear readme
[+] use database - mongodb
[+] code style and folder structure clear
[+] state is good, each user has models for its and the state based on the state on it.

[-] no test
[-] birthday calculation is wrong
[-] all in one commit

@fadhlichan  , can you improve based on the above feedback ?

**Comment by fadhlichan** [comment]
> [+] clear readme [+] use database - mongodb [+] code style and folder structure clear [+] state is good, each user has models for its and the state based on the state on it.
> 
> [-] no test [-] birthday calculation is wrong [-] all in one commit
> 
> @fadhlichan , can you improve based on the above feedback ?

Sure. I will improve it ASAP.

**Comment by fadhlichan** [comment]
I've improved my code

[+] Add tests
[+] Fix: birthday calculation
[+] Meaningful commits

Hope you can review again @ashwintiwari88
Thanks
